# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.0 on Thu Feb 14 14:28:37 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Experiment", "")
        self.Bind(wx.EVT_MENU, self.OnMenuAddExperiment, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Add")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        self.queue_list = wx.ListBox(self, wx.ID_ANY, choices=["a", "b", "c"])
        self.move_down_queue_button = wx.Button(self, wx.ID_ANY, "v")
        self.move_up_queue_button = wx.Button(self, wx.ID_ANY, "^")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.OnListClick, self.queue_list)
        self.Bind(wx.EVT_BUTTON, self.OnMoveDownListPress, self.move_down_queue_button)
        self.Bind(wx.EVT_BUTTON, self.OnMoveUpListPress, self.move_up_queue_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("frame")
        self.move_down_queue_button.SetMinSize((20, 20))
        self.move_up_queue_button.SetMinSize((20, 20))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.GridBagSizer(0, 0)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.queue_list, (1, 0), (1, 1), 0, 0)
        sizer_2.Add(self.move_down_queue_button, 0, 0, 0)
        sizer_2.Add(self.move_up_queue_button, 0, 0, 0)
        sizer_1.Add(sizer_2, (2, 0), (1, 1), wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnMenuAddExperiment(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'OnMenuAddExperiment' not implemented!")
        event.Skip()

    def OnListClick(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'OnListClick' not implemented!")
        event.Skip()

    def OnMoveDownListPress(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'OnMoveDownListPress' not implemented!")
        event.Skip()

    def OnMoveUpListPress(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'OnMoveUpListPress' not implemented!")
        event.Skip()

# end of class MainFrame
