import wx

MAIN_PAGE_TITLE = "Prober Control"
PAGE_SIZE = (900, 500)
QUEUE_PAGE_NAME = "Queue"
HARDWARE_PAGE_NAME = "Hardware"
BUILD_EXPERIMENTS_PAGE_NAME = "Build"
RESULTS_PAGE_NAME = "Results"
SPACE_SIZE = 4

QUEUE_PANEL_NAME = "Experiments"
HARDWARE_PANEL_NAME = "Hardware"

LIST_PANEL_COLOR = wx.BLACK#wx.Colour(100, 100, 100)
LIST_PANEL_FOREGROUND_COLOR = wx.GREEN#wx.Colour(100, 100, 100)

CONTROL_PANEL_COLOR = wx.WHITE
CONTROL_PANEL_FOREGROUND_COLOR = wx.BLACK#wx.Colour(100, 100, 100)

CONFIG_PATH = "..\..\Configs"
