import wx

MAIN_PAGE_TITLE = "Prober Control"
PAGE_SIZE = (900, 500)
QUEUE_PAGE_NAME = "Queue"
HARDWARE_PAGE_NAME = "Hardware"
BUILD_EXPERIMENTS_PAGE_NAME = "Build"
RESULTS_PAGE_NAME = "Results"
SPACE_SIZE = 4

QUEUE_PANEL_PROPORTION = 1
QUEUE_CONTROL_PANEL_PROPORTION = 1

HARDWARE_PANEL_PROPORTION = 1
HARDWARE_CONTROL_PANEL_PROPORTION = 1

BUILD_PANEL_PROPORTION = 3
BUILD_SCRIPT_PANEL_PROPORTION = 1

RESULTS_EXPERIMENT_PANEL_PROPORTION = 1
RESULTS_FILE_PANEL_PROPORTION = 1

QUEUE_PANEL_NAME = "Experiments"
HARDWARE_PANEL_NAME = "Hardware"

LIST_PANEL_COLOR = wx.Colour(50, 50, 50)
LIST_PANEL_FOREGROUND_COLOR = wx.WHITE#wx.Colour(100, 100, 100)
LIST_PANEL_MARGIN = 5

CONTROL_PANEL_COLOR = wx.WHITE
CONTROL_PANEL_FOREGROUND_COLOR = wx.BLACK#wx.Colour(100, 100, 100)

QUEUE_LABEL_PROPORTION = .1

WORKING_DIRECTORY = "C:\\Users\\wxs5474\\PycharmProjects\\SPAE\\System"

EXPERIMENT_QUEUE_RESULT_ROOT = "Experiment Queues"

QUEUE_FILE_TITLE = "queue_result"
EXPERIMENT_FILE_TITLE = "experiment_result"
