import wx
import os

MAIN_PAGE_TITLE = "PIC Test Control Software"
PAGE_SIZE = (900, 500)
QUEUE_PAGE_NAME = "Queue"
HARDWARE_PAGE_NAME = "Hardware"
BUILD_EXPERIMENTS_PAGE_NAME = "Build"
RESULTS_PAGE_NAME = "Results"
TEST_BUILD_PAGE_NAME = "Build Test"
SPACE_SIZE = 4

QUEUE_PANEL_PROPORTION = 1
QUEUE_CONTROL_PANEL_PROPORTION = 2

HARDWARE_PANEL_PROPORTION = 1
HARDWARE_CONTROL_PANEL_PROPORTION = 1

BUILD_PANEL_PROPORTION = 3
BUILD_SCRIPT_PANEL_PROPORTION = 1

RESULTS_EXPERIMENT_PANEL_PROPORTION = 1
RESULTS_FILE_PANEL_PROPORTION = 1

TEST_BUILD_PANEL_PROPORTION = 1
TEST_BUTTON_PANEL_PROPORTION = 3

TEST_BUILD_PANEL_COLOR = wx.Colour(255, 200, 100)
TEST_BUILD_PANEL_FOREGROUND_COLOR = wx.Colour(0, 0, 0)

LIST_PANEL_COLOR = wx.Colour(50, 50, 50)
LIST_PANEL_FOREGROUND_COLOR = wx.WHITE#wx.Colour(100, 100, 100)

CONTROL_PANEL_COLOR = wx.WHITE
CONTROL_PANEL_FOREGROUND_COLOR = wx.BLACK#wx.Colour(100, 100, 100)

LABEL_PROPORTION = .1

WORKING_DIRECTORY = "/".join(os.getcwd().split("\\")[:-2]) + "/System"

EXPERIMENT_QUEUE_RESULT_ROOT = "Experiment Queues"

QUEUE_FILE_TITLE = "queue_result"
